[project]
name = "azure-well-architected-framework-mindmap"
version = "1.0.0"
description = "A mindmap representation of the Azure Docs and Azure Well-Architected Framework."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "flake8>=7.3.0",
    "isort>=6.0.1",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "pyyaml>=6.0.2",
    "typer>=0.17.4",
]
