# https://taskfile.dev

version: "3"

silent: true

includes:
  git: .taskfiles/git.yml
  py: .taskfiles/python.yml
  node: .taskfiles/node.yml

tasks:
  default:
    desc: Show this help
    cmds:
      - task --list

  init:
    desc: Initialize the project
    deps:
      - py:init
      - node:init

  generate:
    desc: Generate the output
    cmds:
      - task: py:run
      - task: node:run

  test:
    desc: Run the tests
    cmds:
      - task: py:test

  test-coverage:
    desc: Run the tests with coverage
    cmds:
      - task: py:test-coverage

  lint:
    desc: Run the
    deps:
      - py:lint
      - node:lint
