name: Setup prerequisites actions

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Taskfile
      uses: arduino/setup-task@v1
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
        cache: pip
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: "latest"
        cache: npm
    - name: Install dependencies
      run: task init
