name: CI pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  quality-check:
    name: Quality check
    runs-on: ubuntu-latest
    steps:
      - name: Setup prerequisites
        uses: ./github/setup-prerequisites
      - name: Lint code
        run: task lint
      - name: Run tests
        run: task test-coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        continue-on-error: true
        with:
          file: coverage.xml
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

